language: node_js

node_js:
- 6
- stable

before_install:
- yarn global add codecov

script:
- yarn run lint
- yarn run test -- --ci --verbose --coverage
- yarn run test-integration -- --ci --verbose
- yarn run remap-integration -- --check --list-different

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
