language: node_js

node_js:
  - '4'
  - '6'

env:
  - JOB=test

script:
  - if [ "$JOB" = "lint" ]; then yarn run lint; fi
  - if [ "$JOB" = "test" ]; then yarn run test -- --verbose; fi
  - if [ "$JOB" = "test-coverage" ]; then yarn run test-coverage -- --verbose; fi

after_success:
  - if [ "$JOB" != "lint" ]; then yarn run test-integration; fi

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: "stable"
      env: JOB=lint
    - node_js: "stable"
      env: JOB=test-coverage

os:
  - linux
