language: node_js

node_js:
  - '4'
  - '6'

env:
  - JOB=test

before_install:
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codecov

script:
  - if [ "$JOB" = "lint" ]; then yarn run lint; fi
  - if [ "$JOB" = "test" ]; then yarn run test -- --verbose; fi
  - if [ "$JOB" = "test-coverage" ]; then yarn run test -- --coverage --verbose; fi

after_script:
  - greenkeeper-lockfile-upload
  - codecov

after_success:
  - if [ "$JOB" != "lint" ]; then yarn run test-integration; fi

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: "stable"
      env: JOB=lint
    - node_js: "stable"
      env: JOB=test-coverage

os:
  - linux
