language: node_js

node_js:
- 4
- 6
- stable

before_install:
- yarn global add codecov

script:
- yarn run lint
- yarn run test -- --coverage --verbose
- yarn run snap-integration
- yarn run check-diff

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
